weaviate:
  http_host: "10.201.1.80"
  http_port: 8080
  http_secure: false
  grpc_host: "10.201.1.80"
  grpc_port: 50051
  grpc_secure: false
  auth_api_key: "test-secret-key"  # 或者使用环境变量更安全

llm:
  model: "qwen2.5-vl-32b-instruct"
  temperature: 0
  check_model: "qwen-max"

vectorstore:
  index_name: "KGDocument"
  text_key: "text"
  attributes: []

neo4j:
  url: "bolt://10.201.1.80:7687"
  username: "neo4j"
  password: "12345678"
  database: "neo4j"